[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED @ ^3.6.0
    h2zero/NimBLE-Arduino @ ^1.4.2
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DSIMULATE_CAN=0
